# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/*
- master

pool:
  name: local build agent

variables:
  buildConfiguration: 'Release'

stages:
 
- stage: 'Build'
  jobs:
    - job: 'Build'
      steps:
      
      - script: dotnet build --configuration $(buildConfiguration)
        displayName: 'dotnet build $(buildConfiguration)'
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk'
        inputs:
          packageType: sdk
          version: 6.0.x
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: NodeTool@0
        inputs:
          versionSpec: '16.15.x'
          checkLatest: true
      
      - script: dotnet publish --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
        displayName: 'Publishing'
      - task: Npm@1
        displayName: 'Install Dependencies'
        inputs:
          command: 'install'
          workingDir: 'ClientApp'
      
      # - task: Npm@1
      #   displayName: 'Testing'
      #   inputs:
      #      command: 'custom'
      #      workingDir: 'ClientApp'
      #      customCommand: 'run test'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      
      # - task: DotNetCoreCLI@2
      #   displayName: Publish Project
      #   inputs:
      #     command: 'publish'
      #     publishWebProjects: true
      #     arguments: '--configuration $(buildConfiguration)'
      #     zipAfterPublish: true