# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/*
- master

pool:
  name: local build agent

variables:
  buildConfiguration: 'Release'

stages:
 
- stage: 'Build'
  jobs:
    - job: 'Build'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.15.1'
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'dotnetdemo'
      
      - script: dotnet build --configuration $(buildConfiguration)
        displayName: 'dotnet build $(buildConfiguration)'
      - task: UseDotNet@2
        displayName: 'Install .NET Core SDK'
        inputs:
          version: 5.0.x
          performMultiLevelLookup: true
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        inputs:
         command: 'restore'
         feedsToUse: 'select'
         vstsFeed: 'my-vsts-feed' # A series of numbers and letters
    
      - task: DotNetCoreCLI@2
        displayName: Publish Project
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration $(buildConfiguration)'
          zipAfterPublish: true